### ISSUE TITLE
How fine grained can the access management be using S3 as qabel-storage

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-accounting#1]

**Comment by audax** [comment]
# Actual implementation:

qabel-accounting has an AWS account with the rights: ListBucket, GetObject, PutObject, DeleteObject and can create federation tokens.

Users that need write access to their prefix on S3 can get a federation token that allows them to list, get, put and delete objects in the bucket, but only within their given prefix. Those tokens are valid for at least 10 minutes and up to 32 hours.

The federation token can have arbitrary additional restrictions attached, but it cannot be revoked.
