### ISSUE TITLE
Respect the Accept-Language header

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-accounting#35]
Validation error messages should be localized in EN/DE. See https://docs.djangoproject.com/en/1.9/ref/middleware/#module-django.middleware.locale

**Comment by audax** [comment]
Please check that all messages from the API are localized (even requests like /auth/password/change )

**Comment by dannywerner** [comment]
change password don't work. iam can send any 'old_password' or to short new password and get a success

**Comment by jasinai** [comment]
django-rest-framework was already translated. I opened a pull request in django-rest-auth, I hope they will merge it soon.

**Comment by audax** [comment]
Please link that PR in the comments here

**Comment by jasinai** [comment]
This is the PR Tivix/django-rest-auth#165
