### ISSUE TITLE
provide client version information

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-accounting#55]
The clients need a source to get the latest version number to know when an update is available.

*Maybe based on a file that could be created by any external job (like the ci server) and contains the latest version number in some structure the accounting server doesn't even have to understand.*

**Comment by jasinai** [comment]
Our web server will have this file and we will update this file, if needed. I will talk with our web developer.

**Comment by jasinai** [comment]
You can find the file at https://files.qabel.de/etc/versions.json
