### ISSUE TITLE
Accounting vulnerable against brute force

### ISSUE THREAD

**Issue by roeslpa** [Qabel/qabel-accounting#60]
Number of login requests with wrong password is not limited => brute force is not prevented! Since the password length is min six characters online guessing can be successful really quickly. Proposal: max 5 wrong password requests, min 8 characters password.

**Comment by audax** [comment]
5 wrong requests for each user id, or for each IP?

**Comment by roeslpa** [comment]
I guess per account would lead to the attack, that you could block a foreign account. So per IP would be better for this case but easy to circumvent (with a little speed loss)?!

**Comment by roeslpa** [comment]
I would propose something like 5 per IP and 50 per account (or for now only 50 per account). After 50 per account the user is informed per mail about the incident and requested to update the password inside the app or with a certain link (or for now only inside the app).

**Comment by mr-gosh** [comment]
I would suggest in addition to anything else to limit the password attempts to 1 per 3 seconds to reduce attack surface through time limiting...

**Comment by audax** [comment]
This has no massive security implication as long as the attacker does not also retrieve the private key of the user.

The usual rate limiting from nginx will of course be applied to the accounting server.

**Comment by roeslpa** [comment]
Since users often use the same password for several services this has a huge impact on the self understanding of Qabel regarding security if such an easy attack is not prevented. I don't know the configuration of the nginx but yesterday I was able to request several thousands of logins tries  for one account without any restrictions.

**Comment by audax** [comment]
Were the servers you were testing against the live servers with a rate limiting config applied?

**Comment by thechauffeur** [comment]
@audax I guess he weren't and as he wrote he doesn't know the config of the nginx.

@roeslpa imagine we would impose a limit of 5 requests per account per minute (regarding the API calls which need a password) BUT we would not lock the account, nor requesting a new password via mail. What are the remaining problems in your opinion and would you think this is sufficient for now?
