### ISSUE TITLE
Storing S3 credentials for travis

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-accounting#7]
Storing credentials encrypted in .travis.yml or in environment variables:

Those variables can be defined directly in the travis account or .travis.yml,  but pull requests from external repositories will not be built with these variables active.

They are available to pull requests that originate in the same repository. To run these automatic tests in pull requests, we have to first push the branch and then send the pull request. This is a change in policy, but I don't see a way around it.

**Comment by jan-schreib** [comment]
When the s3 components are finished and tested, this should not really concern us, should it? We could also turn off the s3 tests as soon as they are stable. As long as we have no external contributers your approach doesn't sound too bad.

**Comment by audax** [comment]
As soon as this is decided, we can test it with #10

**Comment by audax** [comment]
They are now stored in the travis env.
