### ISSUE TITLE
Landing page after email confirmation missing

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-accounting#87]
It redirects to qabel.de, it should at least redirect to qabel.de/email-confirmed/ or something like this. The page on qabel.de needs to be created first.

**Comment by enkore** [comment]
Uhm, we currently have no CSS/markup at all for this, do we?

**Comment by audax** [comment]
Yep. No mocks, no markup. You can probably get the templates from qabel.de…

**Comment by audax** [comment]
Solved, we now have templates and pages and stuff
