### ISSUE TITLE
Confirmation does not work

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-accounting#89]
Every day I receive a mail to confirm my email (sometimes twice at the same time), every day I click on the link and every next day I get a new mail ...

Example link: http://accounting.qabel.org/account-confirm-email/f6trxtnuqmg0j1gs1mia8ubbvhs2yp9w6vz91bbg6dguuotj93q579eynhoodup4/

**Comment by audax** [comment]
This explains the amount of email confirmations. The trigger to send a new confirmation mail is wrong, your account is of course already activated.
